export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_USER = 'CLEAR_USER';

export const ADD_COMPLAINT = 'ADD_COMPLAINT';
export const COMPLAINT_ERROR = 'COMPLAINT_ERROR';
export const GET_MY_COMPLAINTS = 'GET_MY_COMPLAINTS';
export const DELETE_COMPLAINT = 'DELETE_COMPLAINT';
export const CLEAR_COMPLAINTS = 'CLEAR_COMPLAINTS';

export const ADD_APPLICATION = 'ADD_APPLICATION';
export const APPLICATION_ERROR = 'APPLICATION_ERROR';
export const GET_MY_APPLICATION = 'GET_MY_APPLICATION';
export const DELETE_APPLICATION = 'DELETE_APPLICATION';
export const CLEAR_APPLICATION = 'CLEAR_APPLICATION';

